# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Life as a Teenage ECE Student 
mail: zengzhuoxi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        This is a place where you can find updates on projects 
        I've been currently working on.
        Also, where I amuse myself by writing blogs nobody reads.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manoflast3.github.io" # the base hostname & protocol for your site
twitter_username: zeng_derek 
github_username: manoflast3 

# Build settings
markdown: kramdown
